language: node_js
node_js:
  - '4.4.2'

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - rvm install 2.3.1

install:
  - bundle install
  - npm install

script:
  - npm run dev
  - npm test
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then npm run prod; fi
