###### TODO add a development domain and URL.
## Configuration URLs
domain: 'dev.example.com'
url: 'http://dev.example.com'

###### TODO development build/serve configuration, if any

## Sass configuration
sass:
  style: expanded
