title: Jean and Oliver
author:
  name: Jean Flanagan and Oliver Pattison
description: 'Photos and notes of Jean Flanagan and Oliver Pattison during our travels.'
end_note: 'These are the photos and notes of Jean Flanagan and [Oliver Pattison](https://olivermak.es) during our trip to Vermont in October 2016.'

license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'

# Content

## Referenced URLs (internal and external links for inline use)
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
  source: https://github.com/opattison/jeanandoliver
  subscribe:
    full: /full.xml

# Site configuration

## Gems configuration
gems:
  - sass
  - jekyll/imgix

## Imgix configuration
imgix:
  source: jeanandoliver.imgix.net
  secure_url_token: DTlnqH2kw7tF7rQH

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

## Permalink configuration
permalink: /:year/:title/

## Collections
collections:
  patterns:
    output: false
  patterns-categories:
    output: true
    permalink: patterns/:path/
  photos:
    output: true
    permalink: /:year/:categories/:path/

defaults:
  - scope:
      type: patterns-categories
    values:
      layout: pattern
      category: patterns
  - scope:
      type: photos
    values:
      layout: photo

## Sass configuration
sass:
  sass_dir: _source/scss
  style: compressed

## Project configuration
include:
  - _feeds
  - _pages

exclude:
  - _config
  - Gemfile*
  - node_modules
  - package.json

## Configuration URLs
domain: 'jeanandoliver.space'
url: 'https://jeanandoliver.space'
patterns_url: /patterns
image_url: /images
icon_url: /icons
resources_url: /resources

## srcset implementation
sizes: '(min-width: 28em) 75vw, 100vw'
sizes_photo: '(min-width: 60em) 88.5vw, (min-width: 40em) 94vw, 100vw'
sizes_item: '(min-width: 40em) 43.333333vw, (min-width: 28em) 46.875vw, 100vw'
srcset:
  - 640
  - 720
  - 900
  - 1280
  - 1440
srcset_item:
  - 640
  - 720
  - 900
  - 1280

## Mapbox authentication and configuration
mapbox:
  key: pk.eyJ1Ijoib3BhdHRpc29uIiwiYSI6Il9DU3p1MEkifQ.3cvRQB5hVIONMpDAflBUNw
  style: mapbox://styles/opattison/ciuoegxtl007i2inykyztlus6
  attribution: 'Map data <a href="https://www.mapbox.com/about/maps/">© Mapbox</a>, <a href="http://www.openstreetmap.org/copyright">© OpenStreetMap</a> contributors.'
