###### TODO replace these defaults; add a site description
title: Jean and Oliver
author:
  name: Jean Flanagan and Oliver Pattison
description: 'Photos and notes from Jean Flanagan and Oliver Pattison about our travels.'
end_note: 'These are photos and notes from Jean Flanagan and [Oliver Pattison](https://olivermak.es) about our trip to Vermont in October 2016.'

license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'

# Content

## Referenced URLs (internal and external links for inline use)
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
  subscribe:
    full: /full.xml

# Site configuration

## Gems configuration
gems:
  - sass
  - jekyll/imgix

## Imgix configuration
imgix:
  source: jeanandoliver.imgix.net
  secure_url_token: DTlnqH2kw7tF7rQH

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

###### TODO choose a URL structure for posts
## Permalink configuration
permalink: /:year/:title/

## Collections
collections:
  patterns:
    output: false
  patterns-categories:
    output: true
    permalink: patterns/:path/
  photos:
    output: true
    permalink: /:year/:categories/:path

defaults:
  - scope:
      type: patterns-categories
    values:
      layout: pattern
      category: patterns
  - scope:
      type: photos
    values:
      layout: photo

## Sass configuration
sass:
  sass_dir: _source/scss
  style: compressed

## Project configuration
include:
  - _feeds
  - _pages

exclude:
  - _config
  - Gemfile*
  - node_modules
  - package.json

## Configuration URLs
domain: 'jeanandoliver.space'
url: 'http://jeanandoliver.space'
patterns_url: /patterns
image_url: /images
icon_url: /icons
resources_url: /resources

## srcset implementation
sizes_item: '(min-width: 40em) 43.333333vw, (min-width: 28em) 46.875vw, 100vw'
srcset_item:
  - 480
  - 640
  - 720
  - 900
  - 1080
srcset:
  - 480
  - 640
  - 720
  - 900
  - 1080
  - 1260
  - 1440
